# Generated by Django 4.1.4 on 2022-12-08 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couses',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='couses',
            name='image',
            field=models.ImageField(default=None, upload_to='courses/%Y/%m'),
        ),
        migrations.AlterUniqueTogether(
            name='couses',
            unique_together={('sub', 'category_id')},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default=None, upload_to='courses/%Y/%m')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('couses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.couses')),
            ],
            options={
                'unique_together': {('sub', 'couses_id')},
            },
        ),
    ]
